In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import scipy.stats as stats
import seaborn as sea
from sklearn.metrics import log_loss, make_scorer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

In [2]:
president = pd.read_csv('voting_2000_2016_county_data.csv', index_col=1)
# max_v = ipt.groupby(['year', 'state'])['candidatevotes'].transform(func=max)

FileNotFoundError: [Errno 2] No such file or directory: 'voting_2000_2016_county_data.csv'

In [3]:
# president = president.reset_index().set_index(['year', 'county'])

In [4]:
# Import data


for i in range(2010,2017):
    file = pd.read_csv('county_income_{year}.csv'.format(year=str(i)),header=1)
    del file['id']
    file['Geographic Area Name'] = file['Geographic Area Name'].apply(lambda x: x.split('County')[0])
    file['year'] = i
    file.rename(columns = {'Geographic Area Name':'county'}, inplace = True)
    file.set_index(['year', 'county'])
    president += president.merge(file, on=['county'], how='outer')
        


# president_income = president.merge(income, left_on='state', right_on='State', how='left')
# president_income = president_income.reset_index().set_index(['year','state'])

In [5]:
dfs = [df.set_index(['year', 'county']) for df in income.values()]

NameError: name 'income' is not defined

In [ ]:
president_income = president.merge(income, on=['year','state'], how='outer')

In [8]:
president.head()

,year,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version
state,,,,,,,,,,
Alabama,2000,AL,Autauga,1001.0,President,Al Gore,democrat,4942.0,17208,20191203
Alabama,2000,AL,Autauga,1001.0,President,George W. Bush,republican,11993.0,17208,20191203
Alabama,2000,AL,Autauga,1001.0,President,Ralph Nader,green,160.0,17208,20191203
Alabama,2000,AL,Autauga,1001.0,President,Other,NaN,113.0,17208,20191203
Alabama,2000,AL,Baldwin,1003.0,President,Al Gore,democrat,13997.0,56480,20191203

In [ ]:
# income.to_csv(r'county_income_2000-2016.xlsx')

In [ ]:
# file = pd.read_csv('county_income_2010.csv', header=1, index_col=1)
# file = pd.DataFrame(file)
# file.index.names=['county']
# file.rename(index=str.lower)
# del file['id']

# file.head()

In [ ]:
president_income = president_income.reset_index().set_index(['year','state'])

In [47]:
file = pd.read_csv('county_income_2012.csv', header=1)
file = pd.DataFrame(file)

# file['Geographic Area Name'] = file['Geographic Area Name'].apply(lambda x: x.split('County')[0])
del file['id']
file.rename(columns = {'Geographic Area Name':'county'}, inplace = True)
file['year'] = 2012

In [26]:
# president.rename(columns={'year':'year_x'}, inplace = True)

In [34]:
president['year_x']>=2010

state
Alabama    False
Alabama    False
Alabama    False
Alabama    False
Alabama    False
           ...
Alaska      True
Alaska      True
Alaska      True
Alaska      True
Alaska      True
Name: year_x, Length: 50524, dtype: bool

In [46]:
income.head()

,county,Total!!Estimate!!Households,Total!!Margin of Error!!Households,Total!!Estimate!!One race!!White,Total!!Margin of Error!!One race!!White,Total!!Estimate!!One race!!Black or African American,Total!!Margin of Error!!One race!!Black or African American,Total!!Estimate!!One race!!American Indian and Alaska Native,Total!!Margin of Error!!One race!!American Indian and Alaska Native,Total!!Estimate!!One race!!Asian,...,Median income (dollars)!!Estimate!!NONFAMILY HOUSEHOLDS!!Male householder!!Not living alone,Median income (dollars)!!Margin of Error!!NONFAMILY HOUSEHOLDS!!Male householder!!Not living alone,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Household income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Household income in the past 12 months,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Family income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Family income in the past 12 months,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Nonfamily income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Nonfamily income in the past 12 months,Median income (dollars)!!Margin of Error!!One race!!American Indian and Alaska Native,year
0,"Ouachita Parish, Louisiana",58133,1702,64.3,1.7,33.7,1.7,N,N,N,...,36425,10827,(X),(X),(X),(X),(X),(X),N,2012
1,"Rapides Parish, Louisiana",49299,1669,68.7,2.0,28.5,1.9,N,N,N,...,42733,12754,(X),(X),(X),(X),(X),(X),26004,2012
2,"St. Landry Parish, Louisiana",30937,1042,60.4,1.9,37.4,2.6,N,N,N,...,30710,19621,(X),(X),(X),(X),(X),(X),**,2012
3,"St. Tammany Parish, Louisiana",89333,1323,85.8,0.9,10.3,0.8,N,N,N,...,54475,37906,(X),(X),(X),(X),(X),(X),13836,2012
4,"Tangipahoa Parish, Louisiana",43653,1545,73.2,2.2,25.2,2.4,N,N,N,...,53073,44212,(X),(X),(X),(X),(X),(X),21256,2012

In [ ]:
# pd.set_option('display.max_rows', None)
income.to_csv(r'county_income_2000-2016.csv')

In [ ]:
# president_income = president.merge(income, left_on='state', right_on='State', how='left')
# president_income = president_income.reset_index().set_index(['year','state'])
for i in range(2010,2017):
    print('county_income_{year}.csv'.format(year=str(i)))

In [48]:
# president_income = president.merge(income, left_on='state', right_on='State', how='left')
# president_income = president_income.reset_index().set_index(['year','state'])
income = file
president_income = president.merge(income, left_on='county', right_on='county', how='left')
president_income.tail()

,year_x,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version,...,Median income (dollars)!!Estimate!!NONFAMILY HOUSEHOLDS!!Male householder!!Not living alone,Median income (dollars)!!Margin of Error!!NONFAMILY HOUSEHOLDS!!Male householder!!Not living alone,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Household income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Household income in the past 12 months,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Family income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Family income in the past 12 months,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Nonfamily income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Nonfamily income in the past 12 months,Median income (dollars)!!Margin of Error!!One race!!American Indian and Alaska Native,year
50519,2016,AK,District 40,2040.0,President,Donald Trump,republican,1377.0,4610,20191203,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50520,2016,AK,District 40,2040.0,President,Other,NaN,895.0,4610,20191203,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50521,2016,NaN,District 99,2099.0,President,Hillary Clinton,democrat,274.0,5056,20191203,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50522,2016,NaN,District 99,2099.0,President,Donald Trump,republican,40.0,5056,20191203,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50523,2016,NaN,District 99,2099.0,President,Other,NaN,28.0,5056,20191203,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
income.head()

,county,Total!!Estimate!!Households,Total!!Margin of Error!!Households,Total!!Estimate!!One race!!White,Total!!Margin of Error!!One race!!White,Total!!Estimate!!One race!!Black or African American,Total!!Margin of Error!!One race!!Black or African American,Total!!Estimate!!One race!!American Indian and Alaska Native,Total!!Margin of Error!!One race!!American Indian and Alaska Native,Total!!Estimate!!One race!!Asian,...,Median income (dollars)!!Estimate!!NONFAMILY HOUSEHOLDS!!Male householder!!Not living alone,Median income (dollars)!!Margin of Error!!NONFAMILY HOUSEHOLDS!!Male householder!!Not living alone,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Household income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Household income in the past 12 months,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Family income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Family income in the past 12 months,Median income (dollars)!!Estimate!!PERCENT IMPUTED!!Nonfamily income in the past 12 months,Median income (dollars)!!Margin of Error!!PERCENT IMPUTED!!Nonfamily income in the past 12 months,Median income (dollars)!!Margin of Error!!One race!!American Indian and Alaska Native,year
0,"Ouachita Parish, Louisiana",58133,1702,64.3,1.7,33.7,1.7,N,N,N,...,36425,10827,(X),(X),(X),(X),(X),(X),N,2012
1,"Rapides Parish, Louisiana",49299,1669,68.7,2.0,28.5,1.9,N,N,N,...,42733,12754,(X),(X),(X),(X),(X),(X),26004,2012
2,"St. Landry Parish, Louisiana",30937,1042,60.4,1.9,37.4,2.6,N,N,N,...,30710,19621,(X),(X),(X),(X),(X),(X),**,2012
3,"St. Tammany Parish, Louisiana",89333,1323,85.8,0.9,10.3,0.8,N,N,N,...,54475,37906,(X),(X),(X),(X),(X),(X),13836,2012
4,"Tangipahoa Parish, Louisiana",43653,1545,73.2,2.2,25.2,2.4,N,N,N,...,53073,44212,(X),(X),(X),(X),(X),(X),21256,2012

In [19]:
# Import data
income = file


# Merge and reset index to create main dataframe
president_income = president.merge(income, left_on='county', right_on='county', how='left')
president_income = president_income.reset_index().set_index(['year_x','county'])


# Isolate [year] Median Income and [year] Standard Error data
median_col = income.columns.str.contains('year')
Median_Income = income.iloc[:,median_col]
error_col = income.columns.str.contains('year')
Standard_Error = income.iloc[:,error_col]


# Change Median and Error data to have 'State', 'year', and Median/Error in specified columns
median = pd.melt(income, id_vars='county',value_vars=income.columns[median_col],var_name='year')
error = pd.melt(income, id_vars='county',value_vars=income.columns[error_col],var_name='year')


# Edit column names to match data change above
median['year'] = median['year'].str.replace('Median Income','')
median = median.rename(columns = {'value':'Median Income'})
error['year'] = error['year'].str.replace('Standard Error','')
error = error.rename(columns = {'value':'Standard Error'})


#Edit 'State' to match 'state' in main dataframe
median = median.rename(columns = {'State':'state'})
error = error.rename(columns = {'State':'state'})

median['year'] = pd.to_numeric(median['year'])
error['year'] = pd.to_numeric(median['year'])

median = median.set_index(['year','state'])
error = error.set_index(['year','state'])

president_income = president_income.reset_index()
politics = president_income[['year','state','office','candidate', 'party', 'writein', 'candidatevotes', 'totalvotes']].copy()

median = median.reset_index()
error = error.reset_index()


# Merge Median Income and Standard Error columns into main dataframe
income_politics_table = politics.merge(median, on=['year','state'], how='outer')
income_politics_table = income_politics_table.merge(error, on=['year','state'], how='outer')
ipt = income_politics_table

ValueError: Unable to parse string "Total!!Estimate!!HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER!!15 to 24 years" at position 0